on:
  push:
  workflow_dispatch:

jobs:
  build:
    # do a test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.10", "3.11"]
    steps:
      uses: actions/checkout@v4
      uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      name: build
      run: pip install .
