on:
  push:
  workflow_dispatch:

# from https://github.com/pypa/cibuildwheel?tab=readme-ov-file#example-setup
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # , ubuntu-24.04-arm, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: install
      run: python -m pip install cibuildwheel==2.23.3
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl
